### ISSUE TITLE
STM support

### ISSUE THREAD

**Issue by Yanjiong** [hwangcc23/ptm2human#3]
Any plan to support STM?

**Comment by hwangcc23** [comment]
@Yanjiong What is STM? Could you explain it or provide the link to its document on infocenter.arm.com? Thanks.

**Comment by Yanjiong** [comment]
@hwangcc23 http://infocenter.arm.com/help/topic/com.arm.doc.ihi0054b/IHI0054B_stm_architecture_specification_v1_1.pdf

**Comment by hwangcc23** [comment]
No plan to support STM since I am pretty busy at my job in this year, and I don't have any platform w/ STM for development and testing.
