### ISSUE TITLE
Decodeng Atom5 and Atom6

### ISSUE THREAD

**Issue by stas-ibragimov** [hwangcc23/ptm2human#8]
Hello!

Decoding of Atom5 and Atom6 packets is sometimes wrong.
For example, 0xD4 (0b11010100) is decoded as Atom5 with incorrect ABC, but according to IHI0064D this packet must be decoded as Atom6.

Table 6-21:
Atom Format 5 0b11110101 and 0b11010101 - 0b11010111 
Atom Format 6 0b11000000 - **0b11010100** and 0b11100000 - 0b11110100

**Comment by hwangcc23** [comment]
Thanks for reporting the issue.
It should be fixed by the change just submitted.

**Comment by stas-ibragimov** [comment]
Thank you!
